name: decommission-on-pull-close

on:
  pull_request:
    types: [closed]

jobs:
  decommission:
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6
    - name: extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${{ steps.branch-name.outputs.head_ref_branch }})"
      id: extract_branch
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        # Can be "open", "closed", or "all".  Defaults to "open".
        state: closed
    - name: print branch name
      run: |
        echo "${{ steps.extract_branch.outputs.branch }}"
    - name: get-pr-ref
      run: echo "merge ref is ${MERGE_REF}"
      env:
        MERGE_REF: "refs/pull/${{ steps.findPr.outputs.pr }}/merge"
    - name: print mergeref
      run: | 
        echo ${MERGE_REF}